#!/usr/bin/env python3
"""
CROVIA Discussion Sender
========================

Sends Model Card Enhancement suggestions as HuggingFace Discussions.
Maintains CROVIA's neutral, helpful tone - no accusations, only observations.

Rate limited to avoid spam (max 50/day by default).
Tracks all sent discussions for monitoring acceptance.

Author: Crovia Engineering
"""

import json
import os
import hashlib
from concurrent.futures import ThreadPoolExecutor, TimeoutError as FuturesTimeoutError
from datetime import datetime, timezone, timedelta
from typing import Dict, List, Any, Optional
from dataclasses import dataclass, asdict
import time

# Try to import huggingface_hub
try:
    from huggingface_hub import HfApi, hf_hub_url
    HF_AVAILABLE = True
except ImportError:
    HF_AVAILABLE = False

# CROVIA branding constants
CROVIA_SIGNATURE = """
---

*This suggestion was generated by [Crovia](https://croviatrust.com) — the AI transparency observation layer.*

Crovia does **not** accuse or judge. It observes publicly available information and suggests documentation improvements.

If this suggestion is helpful, consider adding the recommended sections to your model card.
If not applicable, feel free to close this discussion.

**Learn more:** [croviatrust.com](https://croviatrust.com) · [What is Crovia?](https://croviatrust.com/how-to-read.html)
"""

DISCUSSION_TITLE = "📋 Documentation Enhancement Suggestion"

@dataclass
class SentDiscussion:
    """Record of a sent discussion."""
    target_id: str
    repo_id: str
    repo_type: str
    discussion_url: Optional[str]
    discussion_num: Optional[int]
    sent_at: str
    status: str  # sent, failed, dry_run
    error: Optional[str] = None
    package_hash: str = ""
    
    def to_dict(self) -> Dict[str, Any]:
        return asdict(self)


class DiscussionSender:
    """
    Sends enhancement suggestions as HuggingFace Discussions.
    
    Respects rate limits and maintains CROVIA's neutral tone.
    """
    
    def __init__(self, hf_token: Optional[str] = None, dry_run: bool = False):
        self.hf_token = hf_token or os.getenv("HF_TOKEN")
        self.dry_run = dry_run
        self.api = HfApi(token=self.hf_token) if HF_AVAILABLE and self.hf_token else None
        
        self.sent_today = 0
        self.max_per_day = int(os.getenv("CROVIA_MAX_DISCUSSIONS_PER_DAY", "50"))
        self.delay_between = float(os.getenv("CROVIA_DISCUSSION_DELAY_SEC", "5"))
        
        self.sent_log: List[SentDiscussion] = []
        self.stats = {"sent": 0, "failed": 0, "skipped": 0, "dry_run": 0}
    
    def _format_discussion_body(self, enhancement_md: str) -> str:
        """Format the discussion body with CROVIA signature."""
        return f"""{enhancement_md}

{CROVIA_SIGNATURE}
"""
    
    def _extract_repo_info(self, target: Dict) -> tuple:
        """Extract repo_id and repo_type from target."""
        target_id = target.get("target_id", "")
        source = target.get("source", "huggingface")  # Default to HF
        name = target.get("name", target_id)  # Use target_id as name if not present
        tipo = target.get("tipo_target", "model")
        
        # Only HuggingFace repos support discussions
        # "registry" targets are also on HuggingFace
        if source not in ["huggingface", "registry", ""]:  # Empty source also means HF
            return None, None
        
        repo_type = "dataset" if tipo == "dataset" else "model"
        return name, repo_type
    
    def can_send_more(self) -> bool:
        """Check if we can send more discussions today."""
        return self.sent_today < self.max_per_day
    
    def send_discussion(self, target: Dict, enhancement_md: str, package_hash: str = "") -> SentDiscussion:
        """
        Send a single discussion to a HuggingFace repo.
        
        Returns SentDiscussion record.
        """
        repo_id, repo_type = self._extract_repo_info(target)
        target_id = target.get("target_id", "")
        now = datetime.now(timezone.utc).isoformat().replace("+00:00", "Z")
        
        # Skip non-HF targets
        if not repo_id:
            self.stats["skipped"] += 1
            return SentDiscussion(
                target_id=target_id,
                repo_id="",
                repo_type="",
                discussion_url=None,
                discussion_num=None,
                sent_at=now,
                status="skipped",
                error="Not a HuggingFace repo",
                package_hash=package_hash,
            )
        
        # Check rate limit
        if not self.can_send_more():
            self.stats["skipped"] += 1
            return SentDiscussion(
                target_id=target_id,
                repo_id=repo_id,
                repo_type=repo_type,
                discussion_url=None,
                discussion_num=None,
                sent_at=now,
                status="skipped",
                error="Daily rate limit reached",
                package_hash=package_hash,
            )
        
        # Dry run mode
        if self.dry_run:
            self.stats["dry_run"] += 1
            self.sent_today += 1
            record = SentDiscussion(
                target_id=target_id,
                repo_id=repo_id,
                repo_type=repo_type,
                discussion_url=f"https://huggingface.co/{repo_id}/discussions/DRY_RUN",
                discussion_num=0,
                sent_at=now,
                status="dry_run",
                package_hash=package_hash,
            )
            self.sent_log.append(record)
            return record
        
        # Check API availability
        if not self.api:
            self.stats["failed"] += 1
            return SentDiscussion(
                target_id=target_id,
                repo_id=repo_id,
                repo_type=repo_type,
                discussion_url=None,
                discussion_num=None,
                sent_at=now,
                status="failed",
                error="HuggingFace API not available",
                package_hash=package_hash,
            )
        
        # Send the discussion (with retry on 429)
        max_retries = int(os.getenv("CROVIA_DISCUSSION_MAX_RETRIES", "3"))
        api_timeout = int(os.getenv("CROVIA_DISCUSSION_TIMEOUT_SEC", "30"))
        for attempt in range(max_retries + 1):
            try:
                body = self._format_discussion_body(enhancement_md)
                
                with ThreadPoolExecutor(max_workers=1) as executor:
                    future = executor.submit(
                        self.api.create_discussion,
                        repo_id=repo_id,
                        title=DISCUSSION_TITLE,
                        description=body,
                        repo_type=repo_type,
                    )
                    discussion = future.result(timeout=api_timeout)
                
                discussion_num = discussion.num if hasattr(discussion, 'num') else None
                discussion_url = f"https://huggingface.co/{repo_id}/discussions/{discussion_num}" if discussion_num else None
                
                self.stats["sent"] += 1
                self.sent_today += 1
                
                record = SentDiscussion(
                    target_id=target_id,
                    repo_id=repo_id,
                    repo_type=repo_type,
                    discussion_url=discussion_url,
                    discussion_num=discussion_num,
                    sent_at=now,
                    status="sent",
                    package_hash=package_hash,
                )
                self.sent_log.append(record)
                
                # Rate limiting delay
                time.sleep(self.delay_between)
                
                return record
                
            except FuturesTimeoutError:
                err_str = f"API timeout after {api_timeout}s"
                self.stats["failed"] += 1
                return SentDiscussion(
                    target_id=target_id,
                    repo_id=repo_id,
                    repo_type=repo_type,
                    discussion_url=None,
                    discussion_num=None,
                    sent_at=now,
                    status="failed",
                    error=err_str,
                    package_hash=package_hash,
                )
            except Exception as e:
                err_str = str(e)
                
                # Handle 429 Too Many Requests — wait and retry
                if "429" in err_str and attempt < max_retries:
                    import re
                    retry_match = re.search(r"Retry after (\d+)", err_str)
                    wait_sec = int(retry_match.group(1)) + 5 if retry_match else 60 * (attempt + 1)
                    wait_sec = min(wait_sec, 600)  # Cap at 10 minutes
                    print(f"    ⏳ Rate limited, waiting {wait_sec}s (attempt {attempt + 1}/{max_retries})...")
                    time.sleep(wait_sec)
                    continue
                
                # Handle 403 Discussions disabled — skip permanently
                if "403" in err_str and "disabled" in err_str.lower():
                    self.stats["skipped"] += 1
                    return SentDiscussion(
                        target_id=target_id,
                        repo_id=repo_id,
                        repo_type=repo_type,
                        discussion_url=None,
                        discussion_num=None,
                        sent_at=now,
                        status="skipped",
                        error="Discussions disabled for this repo",
                        package_hash=package_hash,
                    )
                
                # All other errors
                self.stats["failed"] += 1
                return SentDiscussion(
                    target_id=target_id,
                    repo_id=repo_id,
                    repo_type=repo_type,
                    discussion_url=None,
                    discussion_num=None,
                    sent_at=now,
                    status="failed",
                    error=err_str[:200],
                    package_hash=package_hash,
                )
        
        # Exhausted retries
        self.stats["failed"] += 1
        return SentDiscussion(
            target_id=target_id,
            repo_id=repo_id,
            repo_type=repo_type,
            discussion_url=None,
            discussion_num=None,
            sent_at=now,
            status="failed",
            error="Rate limit: max retries exhausted",
            package_hash=package_hash,
        )
    
    def send_batch(self, targets_with_enhancements: List[tuple]) -> List[SentDiscussion]:
        """
        Send discussions for a batch of (target, enhancement_md, package_hash) tuples.
        """
        results = []
        for target, enhancement_md, package_hash in targets_with_enhancements:
            if not self.can_send_more():
                print(f"  Rate limit reached ({self.max_per_day}/day). Stopping.")
                break
            
            result = self.send_discussion(target, enhancement_md, package_hash)
            results.append(result)
            
            status_icon = "✓" if result.status == "sent" else "○" if result.status == "dry_run" else "✗"
            print(f"  {status_icon} {result.repo_id}: {result.status}")
        
        return results
    
    def get_stats(self) -> Dict[str, Any]:
        """Return sending statistics."""
        return {
            **self.stats,
            "sent_today": self.sent_today,
            "max_per_day": self.max_per_day,
            "remaining_today": max(0, self.max_per_day - self.sent_today),
            "timestamp": datetime.now(timezone.utc).isoformat().replace("+00:00", "Z"),
        }
    
    def save_log(self, path: str):
        """Save sent discussion log to JSONL."""
        with open(path, "a", encoding="utf-8") as f:
            for record in self.sent_log:
                f.write(json.dumps(record.to_dict(), ensure_ascii=False) + "\n")
        self.sent_log = []  # Clear after saving


def load_tracker(path: str) -> Dict[str, Any]:
    """Load existing tracker data."""
    if not os.path.exists(path):
        return {"sent": {}, "stats": {"total_sent": 0, "total_accepted": 0, "total_declined": 0}}
    
    with open(path, "r", encoding="utf-8") as f:
        return json.load(f)


def save_tracker(tracker: Dict[str, Any], path: str):
    """Save tracker data."""
    with open(path, "w", encoding="utf-8") as f:
        json.dump(tracker, f, indent=2, ensure_ascii=False)


# ========== CLI ==========

if __name__ == "__main__":
    import argparse
    
    parser = argparse.ArgumentParser(description="CROVIA Discussion Sender")
    parser.add_argument("--input", type=str, help="Input JSONL with targets")
    parser.add_argument("--enhancements", type=str, help="Directory with enhancement .md files")
    parser.add_argument("--limit", type=int, default=5, help="Max discussions to send")
    parser.add_argument("--dry-run", action="store_true", help="Don't actually send, just simulate")
    parser.add_argument("--log", type=str, default="sent_discussions.jsonl", help="Log file")
    args = parser.parse_args()
    
    print("=" * 60)
    print("CROVIA Discussion Sender")
    print("=" * 60)
    
    if not HF_AVAILABLE:
        print("\n⚠️  huggingface_hub not installed. Install with: pip install huggingface_hub")
    
    sender = DiscussionSender(dry_run=args.dry_run)
    
    print(f"\nMode: {'DRY RUN' if args.dry_run else 'LIVE'}")
    print(f"Max per day: {sender.max_per_day}")
    print(f"Limit this run: {args.limit}")
    
    # Demo mode if no input
    if not args.input:
        print("\nNo input file, using demo targets...")
        demo_targets = [
            {
                "target_id": "hf:model:bert-base-uncased",
                "source": "huggingface",
                "tipo_target": "model",
                "name": "bert-base-uncased",
            },
        ]
        demo_enhancement = """## 🎁 Model Card Enhancement Suggestion

This is a demo enhancement package.

### Training Data Transparency

**Status:** Not disclosed

*Recommendation: Add training data documentation.*
"""
        
        batch = [(t, demo_enhancement, "demo_hash") for t in demo_targets[:args.limit]]
    else:
        # Load real targets (supports both JSON and JSONL formats)
        targets = []
        with open(args.input, "r", encoding="utf-8") as f:
            content = f.read().strip()
            if content.startswith("{"):
                # Regular JSON file
                data = json.loads(content)
                if "targets" in data:
                    targets = data["targets"]
                elif isinstance(data, list):
                    targets = data
                else:
                    targets = [data]
            else:
                # JSONL format
                for line in content.split("\n"):
                    if line.strip():
                        targets.append(json.loads(line))
        
        # Load already-contacted IDs to skip (ANY status except failed/skipped)
        # CRITICAL: must include acknowledged, closed, merged, accepted, no_response
        # otherwise the tracker updates status from "sent" → "acknowledged" and
        # the sender thinks the model was never contacted → sends again = SPAM
        SKIP_STATUSES = {"sent", "dry_run", "acknowledged", "closed", "merged", "accepted", "no_response", "declined"}
        sent_ids = set()
        if os.path.exists(args.log):
            with open(args.log, "r", encoding="utf-8") as f:
                for line in f:
                    if line.strip():
                        try:
                            rec = json.loads(line)
                            if rec.get("status") in SKIP_STATUSES:
                                sent_ids.add(rec.get("target_id", ""))
                                sent_ids.add(rec.get("repo_id", ""))
                        except json.JSONDecodeError:
                            pass
        print(f"Already contacted: {len(sent_ids)} IDs (skipping all re-sends)")
        
        batch = []
        for t in targets:
            if len(batch) >= args.limit:
                break
            name = t.get("name", t.get("target_id", ""))
            target_id = t.get("target_id", "")
            if name in sent_ids or target_id in sent_ids:
                continue
            safe_name = name.replace("/", "_").replace(":", "_")
            md_path = os.path.join(args.enhancements or ".", f"{safe_name}.md")
            
            if os.path.exists(md_path):
                with open(md_path, "r", encoding="utf-8") as f:
                    enhancement = f.read()
                batch.append((t, enhancement, hashlib.sha256(enhancement.encode()).hexdigest()[:16]))
    
    print(f"\nSending {len(batch)} discussions...")
    print("-" * 60)
    
    results = sender.send_batch(batch)
    
    stats = sender.get_stats()
    print(f"\n📊 Results:")
    print(f"   Sent: {stats['sent']}")
    print(f"   Dry run: {stats['dry_run']}")
    print(f"   Failed: {stats['failed']}")
    print(f"   Skipped: {stats['skipped']}")
    print(f"   Remaining today: {stats['remaining_today']}")
    
    if not args.dry_run:
        sender.save_log(args.log)
        print(f"\n✅ Log saved to {args.log}")
    
    print("=" * 60)
