#!/usr/bin/env python3
"""
CROVIA GitHub Issue Sender
==========================

Sends Model Card Enhancement suggestions as GitHub Issues.
Expands CROVIA reach beyond HuggingFace to GitHub repositories.

Features:
- Rate limiting (max 30/hour to avoid spam)
- Dry-run mode for testing
- Tracks sent issues
- Neutral, non-accusatory tone

Environment:
- GITHUB_TOKEN: GitHub personal access token with 'repo' scope
- CROVIA_GITHUB_DRY_RUN: Set to "1" for dry-run mode

Author: Crovia Engineering
"""

import json
import os
import hashlib
import time
import urllib.request
import urllib.error
from datetime import datetime, timezone, timedelta
from typing import Dict, List, Any, Optional
from dataclasses import dataclass, asdict

# Rate limiting
MAX_ISSUES_PER_HOUR = 30
DELAY_BETWEEN_ISSUES = 5  # seconds

# Outreach safety defaults
DEFAULT_COOLDOWN_DAYS = 30
DEFAULT_DEDUPE_SCOPE = "org"  # org or repo

# Issue template
ISSUE_TITLE = "📋 Documentation Enhancement Suggestion"

ISSUE_LABELS = ["documentation", "enhancement"]

CROVIA_SIGNATURE = """
---

*This suggestion was generated by [CROVIA](https://croviatrust.com) — the AI transparency observation layer.*

CROVIA does **not** accuse or judge. It observes publicly available information and offers documentation improvements.

If this is helpful, consider adding the suggested sections to your README. If not relevant, feel free to close this issue.

Questions? Visit [croviatrust.com](https://croviatrust.com) or reply to this issue.
"""


@dataclass
class SentIssue:
    """Record of a sent GitHub issue."""
    repo_full_name: str  # owner/repo
    issue_number: Optional[int]
    issue_url: Optional[str]
    sent_at: str
    status: str  # sent, dry_run, failed, skipped
    error: Optional[str]
    package_hash: str
    
    def to_dict(self) -> Dict[str, Any]:
        return asdict(self)


class GitHubIssueSender:
    """Sends enhancement suggestions as GitHub Issues."""
    
    def __init__(self, 
                 github_token: Optional[str] = None,
                 max_per_hour: int = MAX_ISSUES_PER_HOUR,
                 dry_run: bool = False,
                 sent_log_path: Optional[str] = None,
                 cooldown_days: Optional[int] = DEFAULT_COOLDOWN_DAYS,
                 dedupe_scope: Optional[str] = DEFAULT_DEDUPE_SCOPE,
                 dedupe_by_hash: bool = True):
        self.github_token = github_token or os.environ.get("GITHUB_TOKEN")
        self.max_per_hour = max_per_hour
        self.dry_run = dry_run or os.environ.get("CROVIA_GITHUB_DRY_RUN") == "1"
        self.sent_this_hour = 0
        self.sent_log: List[SentIssue] = []
        self.api_base = "https://api.github.com"
        self.sent_log_path = sent_log_path or os.environ.get("CROVIA_GITHUB_SENT_LOG")

        env_cooldown = os.environ.get("CROVIA_GITHUB_COOLDOWN_DAYS")
        if env_cooldown is not None:
            try:
                cooldown_days = int(env_cooldown)
            except ValueError:
                cooldown_days = DEFAULT_COOLDOWN_DAYS
        self.cooldown_days = cooldown_days if cooldown_days is not None else DEFAULT_COOLDOWN_DAYS

        env_scope = os.environ.get("CROVIA_GITHUB_DEDUPE_SCOPE")
        if env_scope:
            dedupe_scope = env_scope.strip().lower()
        self.dedupe_scope = dedupe_scope if dedupe_scope in ("org", "repo") else DEFAULT_DEDUPE_SCOPE

        env_hash = os.environ.get("CROVIA_GITHUB_DEDUPE_HASH")
        if env_hash is not None:
            dedupe_by_hash = env_hash == "1"
        self.dedupe_by_hash = dedupe_by_hash

        self.sent_by_repo: Dict[str, datetime] = {}
        self.sent_by_org: Dict[str, datetime] = {}
        self.sent_hashes: Dict[str, Dict[str, datetime]] = {}
        self._load_sent_index()
    
    def _make_request(self, method: str, endpoint: str, data: Optional[Dict] = None) -> tuple:
        """Make GitHub API request."""
        url = f"{self.api_base}{endpoint}"
        
        headers = {
            "Accept": "application/vnd.github+json",
            "User-Agent": "CroviaTrust/1.0",
            "X-GitHub-Api-Version": "2022-11-28",
        }
        
        if self.github_token:
            headers["Authorization"] = f"Bearer {self.github_token}"
        
        body = None
        if data:
            body = json.dumps(data).encode("utf-8")
            headers["Content-Type"] = "application/json"
        
        req = urllib.request.Request(url, data=body, headers=headers, method=method)
        
        try:
            with urllib.request.urlopen(req, timeout=30) as resp:
                response_data = json.loads(resp.read().decode("utf-8"))
                return resp.status, response_data
        except urllib.error.HTTPError as e:
            error_body = e.read().decode("utf-8") if e.fp else ""
            return e.code, {"error": error_body}
        except Exception as e:
            return 0, {"error": str(e)}
    
    def _check_repo_exists(self, owner: str, repo: str) -> bool:
        """Check if repository exists and is accessible."""
        status, _ = self._make_request("GET", f"/repos/{owner}/{repo}")
        return status == 200
    
    def _check_issues_enabled(self, owner: str, repo: str) -> bool:
        """Check if issues are enabled for the repository."""
        status, data = self._make_request("GET", f"/repos/{owner}/{repo}")
        if status == 200:
            return data.get("has_issues", False)
        return False
    
    def _format_issue_body(self, enhancement_md: str) -> str:
        """Format the issue body with CROVIA signature."""
        return f"""{enhancement_md}

{CROVIA_SIGNATURE}
"""
    
    def _extract_repo_info(self, target: Dict) -> tuple:
        """Extract owner/repo from target."""
        target_id = target.get("target_id", "")
        source = target.get("source", "")
        name = target.get("name", target_id)
        
        # Only GitHub targets
        if source != "github":
            return None, None

        # Parse gh:owner/repo or owner/repo format
        repo_full = name
        if repo_full.startswith("gh:"):
            repo_full = repo_full[3:]
        
        if "/" in repo_full:
            parts = repo_full.split("/", 1)
            return parts[0], parts[1]
        
        return None, None

    def _parse_sent_at(self, sent_at: str) -> Optional[datetime]:
        if not sent_at:
            return None
        try:
            return datetime.fromisoformat(sent_at.replace("Z", "+00:00"))
        except Exception:
            return None

    def _record_latest(self, bucket: Dict[str, datetime], key: str, sent_at: datetime):
        if key not in bucket or sent_at > bucket[key]:
            bucket[key] = sent_at

    def _load_sent_index(self):
        if not self.sent_log_path or not os.path.exists(self.sent_log_path):
            return

        try:
            with open(self.sent_log_path, "r", encoding="utf-8") as f:
                for line in f:
                    line = line.strip()
                    if not line:
                        continue
                    try:
                        record = json.loads(line)
                    except json.JSONDecodeError:
                        continue

                    if record.get("status") != "sent":
                        continue

                    repo_full = record.get("repo_full_name")
                    if not repo_full:
                        continue

                    sent_at = self._parse_sent_at(record.get("sent_at", ""))
                    if not sent_at:
                        continue

                    owner = repo_full.split("/", 1)[0]
                    self._record_latest(self.sent_by_repo, repo_full, sent_at)
                    self._record_latest(self.sent_by_org, owner, sent_at)

                    pkg_hash = record.get("package_hash")
                    if pkg_hash:
                        self.sent_hashes.setdefault(repo_full, {})
                        self._record_latest(self.sent_hashes[repo_full], pkg_hash, sent_at)
        except Exception:
            return

    def _within_cooldown(self, sent_at: Optional[datetime]) -> bool:
        if not sent_at or not self.cooldown_days or self.cooldown_days <= 0:
            return False
        return (datetime.now(timezone.utc) - sent_at) < timedelta(days=self.cooldown_days)

    def _should_skip_history(self, repo_full_name: str, package_hash: str = "") -> Optional[str]:
        owner = repo_full_name.split("/", 1)[0] if repo_full_name else ""

        if self.dedupe_scope == "org":
            last_org = self.sent_by_org.get(owner)
            if self._within_cooldown(last_org):
                return f"Recent outreach to org within {self.cooldown_days}d"

        last_repo = self.sent_by_repo.get(repo_full_name)
        if self._within_cooldown(last_repo):
            return f"Recent outreach to repo within {self.cooldown_days}d"

        if self.dedupe_by_hash and package_hash:
            last_hash = self.sent_hashes.get(repo_full_name, {}).get(package_hash)
            if self._within_cooldown(last_hash):
                return "Duplicate package hash within cooldown"

        return None
    
    def can_send_more(self) -> bool:
        """Check if we can send more issues this hour."""
        return self.sent_this_hour < self.max_per_hour
    
    def send_issue(self, target: Dict, enhancement_md: str, package_hash: str = "") -> SentIssue:
        """Send an enhancement suggestion as a GitHub Issue."""
        dt_now = datetime.now(timezone.utc)
        now = dt_now.isoformat().replace("+00:00", "Z")
        
        owner, repo = self._extract_repo_info(target)
        
        if not owner or not repo:
            return SentIssue(
                repo_full_name=target.get("name", "unknown"),
                issue_number=None,
                issue_url=None,
                sent_at=now,
                status="skipped",
                error="Not a GitHub target or invalid format",
                package_hash=package_hash
            )
        
        repo_full_name = f"{owner}/{repo}"

        skip_reason = self._should_skip_history(repo_full_name, package_hash)
        if skip_reason:
            return SentIssue(
                repo_full_name=repo_full_name,
                issue_number=None,
                issue_url=None,
                sent_at=now,
                status="skipped",
                error=skip_reason,
                package_hash=package_hash
            )
        
        if not self.can_send_more():
            return SentIssue(
                repo_full_name=repo_full_name,
                issue_number=None,
                issue_url=None,
                sent_at=now,
                status="skipped",
                error="Rate limit reached",
                package_hash=package_hash
            )
        
        # Dry run mode
        if self.dry_run:
            self.sent_this_hour += 1
            result = SentIssue(
                repo_full_name=repo_full_name,
                issue_number=None,
                issue_url=None,
                sent_at=now,
                status="dry_run",
                error=None,
                package_hash=package_hash
            )
            self.sent_log.append(result)
            self._record_latest(self.sent_by_repo, repo_full_name, dt_now)
            self._record_latest(self.sent_by_org, owner, dt_now)
            if package_hash:
                self.sent_hashes.setdefault(repo_full_name, {})
                self._record_latest(self.sent_hashes[repo_full_name], package_hash, dt_now)
            return result
        
        # Check token
        if not self.github_token:
            result = SentIssue(
                repo_full_name=repo_full_name,
                issue_number=None,
                issue_url=None,
                sent_at=now,
                status="failed",
                error="No GITHUB_TOKEN provided",
                package_hash=package_hash
            )
            self.sent_log.append(result)
            return result
        
        # Check if repo exists and has issues enabled
        if not self._check_issues_enabled(owner, repo):
            result = SentIssue(
                repo_full_name=repo_full_name,
                issue_number=None,
                issue_url=None,
                sent_at=now,
                status="skipped",
                error="Repository not found or issues disabled",
                package_hash=package_hash
            )
            self.sent_log.append(result)
            return result
        
        # Create issue (with labels by default)
        issue_body = self._format_issue_body(enhancement_md)
        
        status, response = self._make_request(
            "POST",
            f"/repos/{owner}/{repo}/issues",
            {
                "title": ISSUE_TITLE,
                "body": issue_body,
                "labels": ISSUE_LABELS
            }
        )
        
        if status == 201:
            self.sent_this_hour += 1
            time.sleep(DELAY_BETWEEN_ISSUES)  # Rate limiting delay
            
            result = SentIssue(
                repo_full_name=repo_full_name,
                issue_number=response.get("number"),
                issue_url=response.get("html_url"),
                sent_at=now,
                status="sent",
                error=None,
                package_hash=package_hash
            )
            self.sent_log.append(result)
            self._record_latest(self.sent_by_repo, repo_full_name, dt_now)
            self._record_latest(self.sent_by_org, owner, dt_now)
            if package_hash:
                self.sent_hashes.setdefault(repo_full_name, {})
                self._record_latest(self.sent_hashes[repo_full_name], package_hash, dt_now)
            return result
        else:
            error_msg = response.get("error", f"HTTP {status}")
            error_text = error_msg.lower() if isinstance(error_msg, str) else ""
            retry_without_labels = status in (403, 422) and "label" in error_text and (
                "permission" in error_text or "unauthorized" in error_text
            )

            if retry_without_labels:
                status, response = self._make_request(
                    "POST",
                    f"/repos/{owner}/{repo}/issues",
                    {
                        "title": ISSUE_TITLE,
                        "body": issue_body
                    }
                )
                if status == 201:
                    self.sent_this_hour += 1
                    time.sleep(DELAY_BETWEEN_ISSUES)
                    result = SentIssue(
                        repo_full_name=repo_full_name,
                        issue_number=response.get("number"),
                        issue_url=response.get("html_url"),
                        sent_at=now,
                        status="sent",
                        error=None,
                        package_hash=package_hash
                    )
                    self.sent_log.append(result)
                    self._record_latest(self.sent_by_repo, repo_full_name, dt_now)
                    self._record_latest(self.sent_by_org, owner, dt_now)
                    if package_hash:
                        self.sent_hashes.setdefault(repo_full_name, {})
                        self._record_latest(self.sent_hashes[repo_full_name], package_hash, dt_now)
                    return result

                error_msg = response.get("error", f"HTTP {status}")

            result = SentIssue(
                repo_full_name=repo_full_name,
                issue_number=None,
                issue_url=None,
                sent_at=now,
                status="failed",
                error=str(error_msg)[:200],
                package_hash=package_hash
            )
            self.sent_log.append(result)
            return result
    
    def send_batch(self, batch: List[tuple]) -> Dict[str, int]:
        """Send a batch of (target, enhancement_md, hash) tuples."""
        results = {"sent": 0, "dry_run": 0, "failed": 0, "skipped": 0}
        batch_seen_repos = set()
        batch_seen_orgs = set()
        
        for target, enhancement_md, pkg_hash in batch:
            if not self.can_send_more():
                results["skipped"] += len(batch) - sum(results.values())
                break

            owner, repo = self._extract_repo_info(target)
            repo_full = f"{owner}/{repo}" if owner and repo else ""
            if repo_full:
                if repo_full in batch_seen_repos:
                    results["skipped"] += 1
                    print(f"  − {repo_full}: skipped (duplicate repo in batch)")
                    continue
                if self.dedupe_scope == "org" and owner in batch_seen_orgs:
                    results["skipped"] += 1
                    print(f"  − {repo_full}: skipped (duplicate org in batch)")
                    continue
                batch_seen_repos.add(repo_full)
                if self.dedupe_scope == "org":
                    batch_seen_orgs.add(owner)
            
            result = self.send_issue(target, enhancement_md, pkg_hash)
            results[result.status] += 1
            
            owner, repo = self._extract_repo_info(target)
            repo_name = f"{owner}/{repo}" if owner else target.get("name", "unknown")
            
            status_icon = {"sent": "✓", "dry_run": "○", "failed": "✗", "skipped": "−"}
            print(f"  {status_icon.get(result.status, '?')} {repo_name}: {result.status}")
        
        return results
    
    def save_log(self, path: str):
        """Save sent log to JSONL file."""
        with open(path, "a", encoding="utf-8") as f:
            for record in self.sent_log:
                f.write(json.dumps(record.to_dict()) + "\n")
    
    def get_stats(self) -> Dict[str, Any]:
        return {
            "sent_this_hour": self.sent_this_hour,
            "remaining": self.max_per_hour - self.sent_this_hour,
            "dry_run": self.dry_run,
            "log_count": len(self.sent_log)
        }


# ========== CLI ==========

if __name__ == "__main__":
    import argparse
    
    parser = argparse.ArgumentParser(description="CROVIA GitHub Issue Sender")
    parser.add_argument("--input", type=str, help="Input file with targets (JSON/JSONL)")
    parser.add_argument("--enhancements", type=str, help="Directory with enhancement .md files")
    parser.add_argument("--limit", type=int, default=10, help="Max issues to send")
    parser.add_argument("--dry-run", action="store_true", help="Don't actually send")
    parser.add_argument("--log", type=str, default="github_issues_sent.jsonl", help="Log file")
    parser.add_argument("--cooldown-days", type=int, default=None, help="Cooldown window per org/repo")
    parser.add_argument("--dedupe-scope", type=str, default=None, choices=["org", "repo"], help="Dedupe scope")
    parser.add_argument("--dedupe-hash", action="store_true", help="Dedupe by package hash within cooldown")
    parser.add_argument("--no-dedupe-hash", action="store_true", help="Disable package hash dedupe")
    args = parser.parse_args()
    
    print("=" * 60)
    print("CROVIA GitHub Issue Sender")
    print("=" * 60)
    
    dry_run = args.dry_run or os.environ.get("CROVIA_GITHUB_DRY_RUN") == "1"
    if args.no_dedupe_hash:
        dedupe_hash = False
    elif args.dedupe_hash:
        dedupe_hash = True
    else:
        dedupe_hash = True

    sender = GitHubIssueSender(
        dry_run=dry_run,
        sent_log_path=args.log,
        cooldown_days=args.cooldown_days,
        dedupe_scope=args.dedupe_scope,
        dedupe_by_hash=dedupe_hash,
    )
    
    print(f"\nMode: {'DRY RUN' if dry_run else 'LIVE'}")
    print(f"Max per hour: {sender.max_per_hour}")
    print(f"Limit this run: {args.limit}")
    print(f"Cooldown days: {sender.cooldown_days}")
    print(f"Dedupe scope: {sender.dedupe_scope}")
    print(f"Dedupe hash: {sender.dedupe_by_hash}")
    if sender.sent_log_path:
        print(f"Sent log: {sender.sent_log_path}")
    
    # Demo mode if no input
    if not args.input:
        print("\nNo input file - using demo targets...")
        demo_targets = [
            {
                "target_id": "gh:huggingface/transformers",
                "source": "github",
                "name": "huggingface/transformers",
            },
            {
                "target_id": "gh:pytorch/pytorch",
                "source": "github", 
                "name": "pytorch/pytorch",
            },
        ]
        
        demo_enhancement = """## 📋 Documentation Enhancement Suggestion

> This observation was generated by [Crovia](https://croviatrust.com).

### ⚖️ Transparency Checklist

- [ ] Training data sources documented
- [x] License clearly stated
- [ ] Model limitations documented
"""
        
        batch = [(t, demo_enhancement, "demo_hash") for t in demo_targets[:args.limit]]
    else:
        # Load real targets
        targets = []
        with open(args.input, "r", encoding="utf-8") as f:
            content = f.read().strip()
            if content.startswith("{") and "\n{" not in content[:1000]:
                data = json.loads(content)
                if "targets" in data:
                    targets = data["targets"]
                else:
                    targets = [data]
            elif content.startswith("["):
                data = json.loads(content)
                if isinstance(data, list):
                    targets = data
                elif isinstance(data, dict) and "targets" in data:
                    targets = data["targets"]
            else:
                for line in content.split("\n"):
                    line = line.strip()
                    if line and line.startswith("{"):
                        try:
                            targets.append(json.loads(line))
                        except Exception:
                            continue
        
        # Filter only GitHub targets
        github_targets = [t for t in targets if t.get("source") == "github"]
        print(f"\nLoaded {len(targets)} targets, {len(github_targets)} are GitHub")
        
        batch = []
        for t in github_targets[:args.limit]:
            name = t.get("name", t.get("target_id", ""))
            if name.startswith("gh:"):
                name = name[3:]
            safe_name = name.replace("/", "_").replace(":", "_")
            md_path = os.path.join(args.enhancements or ".", f"{safe_name}.md")
            
            if os.path.exists(md_path):
                with open(md_path, "r", encoding="utf-8") as f:
                    enhancement = f.read()
                batch.append((t, enhancement, hashlib.sha256(enhancement.encode()).hexdigest()[:16]))
    
    print(f"\nSending {len(batch)} issues...")
    print("-" * 60)
    
    results = sender.send_batch(batch)
    
    print(f"\n📊 Results:")
    print(f"   Sent: {results['sent']}")
    print(f"   Dry run: {results['dry_run']}")
    print(f"   Failed: {results['failed']}")
    print(f"   Skipped: {results['skipped']}")
    print(f"   Remaining this hour: {sender.max_per_hour - sender.sent_this_hour}")
    
    if sender.sent_log:
        sender.save_log(args.log)
        print(f"\n✅ Log saved to {args.log}")
    
    print("=" * 60)
