#!/usr/bin/env python3
"""
CROVIA Model Card Enhancement Generator
========================================

Generates "irresistible" enhancement packages for model cards.
Instead of asking for transparency, we GIVE valuable documentation.

The package includes:
- Ready-to-use code snippets
- Citation format (BibTeX)
- EU AI Act compliance checklist
- Training data transparency section
- SEO-optimized metadata

Author: Crovia Engineering
"""

import json
import os
import hashlib
from datetime import datetime, timezone
from typing import Dict, List, Any, Optional
from dataclasses import dataclass, asdict
import urllib.request

# Import real analyzer
try:
    from model_card_analyzer import ModelCardAnalyzer, format_analysis_for_enhancement
    ANALYZER_AVAILABLE = True
except ImportError:
    ANALYZER_AVAILABLE = False

ISSUE_LABELS = ["documentation", "enhancement"]
CROVIA_SIGNATURE = """
---
Questions? Visit [croviatrust.com](https://croviatrust.com) or reply to this issue.
"""

README_TRAIN_KEYS = [
    "training data",
    "trained on",
    "dataset",
    "datasets",
    "corpus",
    "data sources",
]
README_EVAL_KEYS = [
    "evaluation",
    "benchmark",
    "results",
    "performance",
    "accuracy",
    "f1",
    "bleu",
    "rouge",
]
README_LIMIT_KEYS = [
    "limitations",
    "risk",
    "warning",
    "caveat",
    "out of scope",
]
README_USAGE_KEYS = [
    "installation",
    "install",
    "usage",
    "quickstart",
    "getting started",
    "requirements",
]
README_LICENSE_KEYS = [
    "license",
    "licence",
    "mit",
    "apache",
    "gpl",
    "bsd",
]


def _contains_any(content: str, keys: List[str]) -> bool:
    if not content:
        return False
    lower = content.lower()
    return any(k in lower for k in keys)


def _fetch_github_readme(repo_full: str) -> str:
    for branch in ("main", "master"):
        url = f"https://raw.githubusercontent.com/{repo_full}/{branch}/README.md"
        try:
            with urllib.request.urlopen(url, timeout=15) as resp:
                return resp.read().decode("utf-8", errors="replace")
        except Exception:
            continue
    return ""


def _analyze_github_readme(repo_full: str) -> Dict[str, Any]:
    readme = _fetch_github_readme(repo_full)
    return {
        "has_readme": bool(readme),
        "has_training_section": _contains_any(readme, README_TRAIN_KEYS),
        "has_evaluation": _contains_any(readme, README_EVAL_KEYS),
        "has_limitations": _contains_any(readme, README_LIMIT_KEYS),
        "has_usage": _contains_any(readme, README_USAGE_KEYS),
        "has_license": _contains_any(readme, README_LICENSE_KEYS),
    }


@dataclass
class EnhancementPackage:
    """A complete model card enhancement package."""
    target_id: str
    target_name: str
    target_url: str
    source: str
    
    # Enhancement sections
    quick_stats: Dict[str, Any]
    code_snippet: str
    citation_bibtex: str
    eu_ai_act_checklist: Dict[str, bool]
    transparency_section: str
    
    # Metadata
    generated_at: str
    package_hash: str
    crovia_version: str = "1.0"
    checklist_title: str = "⚖️ EU AI Act Compliance Checklist"
    checklist_note: str = ""
    
    def to_dict(self) -> Dict[str, Any]:
        return asdict(self)
    
    def to_markdown(self) -> str:
        """Generate the full enhancement as Markdown."""
        checklist_md = "\n".join([
            f"- [{'x' if v else ' '}] {k}" 
            for k, v in self.eu_ai_act_checklist.items()
        ])
        checklist_note = f"\n> {self.checklist_note}\n" if self.checklist_note else ""
        
        return f"""## 📋 Documentation Enhancement Suggestion

> This observation was generated by [Crovia](https://croviatrust.com) — the AI transparency observation layer.
>
> Crovia does **not** accuse or judge. It observes publicly available information and suggests improvements.

---

### 📊 Quick Stats

| Metric | Value |
|--------|-------|
| Source | {self.source} |
| Downloads | {self.quick_stats.get('downloads', 'N/A')} |
| Likes | {self.quick_stats.get('likes', 'N/A')} |
| Last Updated | {self.quick_stats.get('last_updated', 'N/A')} |

---

### 💻 Ready-to-Use Code

```python
{self.code_snippet}
```

---

### 📚 Citation

If you use this model, please cite:

```bibtex
{self.citation_bibtex}
```

---

### {self.checklist_title}
{checklist_note}
{checklist_md}

---

### 🔍 Training Data Transparency

{self.transparency_section}

---

*Enhancement generated by [CROVIA](https://croviatrust.com) · Package ID: `{self.package_hash[:12]}`*
*Generated at: {self.generated_at}*
"""


class EnhancementGenerator:
    """Generates enhancement packages for model cards."""
    
    def __init__(self, use_real_analysis: bool = True):
        self.generated_count = 0
        self.stats = {"generated": 0, "skipped": 0, "errors": 0, "analyzed": 0}
        self.use_real_analysis = use_real_analysis and ANALYZER_AVAILABLE
        self.analyzer = ModelCardAnalyzer() if self.use_real_analysis else None
    
    def _generate_code_snippet(self, target: Dict) -> str:
        """Generate ready-to-use code snippet."""
        source = target.get("source", "")
        name = target.get("name", "")
        
        if source == "huggingface":
            tipo = target.get("tipo_target", "model")
            if tipo == "model":
                return f'''from transformers import AutoModel, AutoTokenizer

model_id = "{name}"
tokenizer = AutoTokenizer.from_pretrained(model_id)
model = AutoModel.from_pretrained(model_id)

# Example usage
inputs = tokenizer("Hello, world!", return_tensors="pt")
outputs = model(**inputs)'''
            else:  # dataset
                return f'''from datasets import load_dataset

dataset = load_dataset("{name}")
print(dataset)

# Access splits
train = dataset["train"]
print(f"Training samples: {{len(train)}}")'''
        
        elif source == "ollama":
            return f'''# Using Ollama CLI
ollama run {name}

# Using Python
import ollama
response = ollama.chat(model='{name}', messages=[
    {{'role': 'user', 'content': 'Hello!'}}
])
print(response['message']['content'])'''
        
        elif source == "github":
            return f'''# Clone the repository
git clone {target.get("url", "")}

# Check README for installation instructions'''
        
        else:
            return f'# See {target.get("url", "")} for usage instructions'
    
    def _generate_citation(self, target: Dict) -> str:
        """Generate BibTeX citation."""
        name = target.get("name", "unknown")
        url = target.get("url", "")
        year = datetime.now().year
        
        # Sanitize name for BibTeX key
        key = name.replace("/", "_").replace("-", "_").replace(".", "_")
        
        return f'''@misc{{{key}_{year},
  author = {{{name.split("/")[0] if "/" in name else "Unknown"}}},
  title = {{{name}}},
  year = {{{year}}},
  url = {{{url}}},
  note = {{Accessed via CROVIA transparency registry}}
}}'''
    
    def _generate_eu_checklist(self, target: Dict) -> Dict[str, bool]:
        """Generate EU AI Act compliance checklist from REAL analysis."""
        metadata = target.get("metadata", {})
        
        # Use real analysis data if available
        return {
            "Training data disclosed": metadata.get("has_training_section", False),
            "License clearly stated": metadata.get("has_license", False),
            "Intended use documented": metadata.get("has_intended_use", False),
            "Model limitations documented": metadata.get("has_limitations", False),
            "Evaluation metrics provided": metadata.get("has_evaluation", False),
            "Bias/fairness analysis": metadata.get("has_bias_section", False),
        }

    def _generate_github_checklist(self, metadata: Dict[str, Any]) -> Dict[str, bool]:
        return {
            "README present": metadata.get("has_readme", False),
            "License mentioned in README": metadata.get("has_license", False),
            "Training data mentioned in README": metadata.get("has_training_section", False),
            "Evaluation/benchmarks mentioned": metadata.get("has_evaluation", False),
            "Limitations/risks mentioned": metadata.get("has_limitations", False),
            "Usage/installation mentioned": metadata.get("has_usage", False),
        }

    def _generate_github_transparency_section(self, metadata: Dict[str, Any]) -> str:
        if metadata.get("has_training_section", False):
            return """**Training Data Status (Observed):** Mentioned in README

This is based solely on the public README text.
"""

        return """**Training Data Status (Observed):** Not observed in README

We did not find explicit training data wording in the public README. This is an observation, not a compliance claim.
"""
    
    def _generate_transparency_section(self, target: Dict) -> str:
        """Generate training data transparency section."""
        metadata = target.get("metadata", {})
        has_training = metadata.get("has_training_section", False)
        declared_datasets = metadata.get("declared_datasets", [])
        
        if has_training and declared_datasets:
            datasets_list = "\n".join([f"- {d}" for d in declared_datasets[:10]])
            return f"""**Training Data Status:** ✅ Disclosed

The following training datasets have been declared:
{datasets_list}

*Source: Model card / README*"""
        
        elif has_training:
            return """**Training Data Status:** ⚠️ Partial

A training section exists but specific datasets are not enumerated.

*Recommendation: Add explicit dataset names and versions for full transparency.*"""
        
        else:
            return """**Training Data Status:** Documentation not found

No training data section was observed in the public model card.

This is an **observation**, not an accusation. Many valid reasons exist for this status.

**If you'd like to improve documentation, consider adding:**
- Dataset names and versions used
- Data collection methodology
- Preprocessing steps applied
- Known limitations

*This may help users understand your model better and prepare for upcoming transparency requirements (e.g., EU AI Act).*"""
    
    def generate_enhancement(self, target: Dict) -> Optional[EnhancementPackage]:
        """Generate a complete enhancement package for a target."""
        try:
            target_id = target.get("target_id", "")
            # Handle different target formats
            name = target.get("name", target_id)  # Use target_id as name if not present
            tipo = target.get("tipo_target", "model")
            
            # Derive source and URL from target_id if not present
            source = target.get("source", "huggingface")  # Default to HF
            if not target.get("url"):
                if tipo == "dataset":
                    url = f"https://huggingface.co/datasets/{target_id}"
                else:
                    url = f"https://huggingface.co/{target_id}"
            else:
                url = target.get("url", "")
            
            # Build popularity dict from flat fields if needed
            popularity = target.get("popularity", {})
            if not popularity:
                popularity = {
                    "downloads": target.get("downloads", 0),
                    "likes": target.get("likes", 0),
                }
            
            if not target_id:
                self.stats["skipped"] += 1
                return None
            
            # Get REAL analysis if available
            metadata = target.get("metadata", {})
            if self.use_real_analysis and self.analyzer and source == "huggingface":
                try:
                    # Extract repo_id from various formats
                    repo_id = name
                    if repo_id.startswith("hf:"):
                        # hf:model:org/name or hf:dataset:org/name
                        parts = repo_id.split(":", 2)
                        repo_id = parts[2] if len(parts) > 2 else parts[-1]
                    
                    analysis = self.analyzer.analyze(repo_id, tipo)
                    metadata = format_analysis_for_enhancement(analysis)
                    self.stats["analyzed"] += 1
                except Exception as e:
                    pass  # Fall back to provided metadata
            
            # Normalize target for code generation
            normalized_target = {
                "target_id": target_id,
                "name": name,
                "source": source,
                "tipo_target": tipo,
                "url": url,
                "popularity": popularity,
                "metadata": metadata,
            }
            
            # Generate all sections
            code_snippet = self._generate_code_snippet(normalized_target)
            citation = self._generate_citation(normalized_target)
            checklist_title = "⚖️ EU AI Act Compliance Checklist"
            checklist_note = ""
            if source == "github":
                repo_full = name[3:] if name.startswith("gh:") else name
                metadata = _analyze_github_readme(repo_full)
                normalized_target["metadata"] = metadata
                checklist = self._generate_github_checklist(metadata)
                transparency = self._generate_github_transparency_section(metadata)
                checklist_title = "🔎 README Observations (public)"
                checklist_note = (
                    "Checklist items are based solely on what we could observe in the public README."
                )
            else:
                checklist = self._generate_eu_checklist(normalized_target)
                transparency = self._generate_transparency_section(normalized_target)
            
            # Create package hash
            content = f"{target_id}{name}{url}"
            package_hash = hashlib.sha256(content.encode()).hexdigest()
            
            package = EnhancementPackage(
                target_id=target_id,
                target_name=name,
                target_url=url,
                source=source,
                quick_stats={
                    "downloads": popularity.get("downloads", "N/A"),
                    "likes": popularity.get("likes", "N/A"),
                    "stars": popularity.get("stars", "N/A"),
                    "last_updated": datetime.now(timezone.utc).strftime("%Y-%m-%d"),
                },
                code_snippet=code_snippet,
                citation_bibtex=citation,
                eu_ai_act_checklist=checklist,
                transparency_section=transparency,
                checklist_title=checklist_title,
                checklist_note=checklist_note,
                generated_at=datetime.now(timezone.utc).isoformat().replace("+00:00", "Z"),
                package_hash=package_hash,
            )
            
            self.stats["generated"] += 1
            return package
            
        except Exception as e:
            self.stats["errors"] += 1
            return None
    
    def generate_batch(self, targets: List[Dict]) -> List[EnhancementPackage]:
        """Generate enhancements for a batch of targets."""
        packages = []
        for target in targets:
            pkg = self.generate_enhancement(target)
            if pkg:
                packages.append(pkg)
        return packages
    
    def get_stats(self) -> Dict[str, Any]:
        """Return generation statistics."""
        return {
            **self.stats,
            "timestamp": datetime.now(timezone.utc).isoformat().replace("+00:00", "Z"),
        }


def calculate_impact(packages: List[EnhancementPackage]) -> Dict[str, Any]:
    """Calculate potential impact of enhancements."""
    total = len(packages)
    
    # Count by transparency status
    no_disclosure = sum(
        1 for p in packages 
        if "Not Disclosed" in p.transparency_section
    )
    partial_disclosure = sum(
        1 for p in packages 
        if "Partial" in p.transparency_section
    )
    full_disclosure = total - no_disclosure - partial_disclosure
    
    # EU AI Act compliance
    compliance_scores = []
    for p in packages:
        score = sum(p.eu_ai_act_checklist.values()) / len(p.eu_ai_act_checklist)
        compliance_scores.append(score)
    
    avg_compliance = sum(compliance_scores) / len(compliance_scores) if compliance_scores else 0
    
    return {
        "total_packages": total,
        "transparency": {
            "no_disclosure": no_disclosure,
            "partial_disclosure": partial_disclosure,
            "full_disclosure": full_disclosure,
            "no_disclosure_pct": round(no_disclosure / total * 100, 1) if total else 0,
        },
        "eu_ai_act": {
            "avg_compliance_score": round(avg_compliance * 100, 1),
            "fully_compliant": sum(1 for s in compliance_scores if s == 1.0),
        },
        "potential_impact": {
            "models_needing_enhancement": no_disclosure + partial_disclosure,
            "if_5pct_accept": round((no_disclosure + partial_disclosure) * 0.05),
            "if_10pct_accept": round((no_disclosure + partial_disclosure) * 0.10),
            "if_20pct_accept": round((no_disclosure + partial_disclosure) * 0.20),
        },
    }


# ========== CLI ==========

if __name__ == "__main__":
    import argparse
    
    parser = argparse.ArgumentParser(description="CROVIA Model Card Enhancement Generator")
    parser.add_argument("--input", type=str, help="Input JSONL file with targets")
    parser.add_argument("--output", type=str, default="enhancements", help="Output directory")
    parser.add_argument("--limit", type=int, default=10, help="Limit number of enhancements")
    parser.add_argument("--dry-run", action="store_true", help="Don't save files, just show stats")
    args = parser.parse_args()
    
    print("=" * 60)
    print("CROVIA Model Card Enhancement Generator")
    print("=" * 60)
    
    # Load targets (supports both JSON and JSONL formats)
    targets = []
    if args.input and os.path.exists(args.input):
        with open(args.input, "r", encoding="utf-8") as f:
            first_char = f.read(1)
            f.seek(0)
            content = f.read().strip()
            
            if first_char == "{" and "\n{" not in content[:1000]:
                data = json.loads(content)
                if isinstance(data, dict) and "targets" in data:
                    targets = data["targets"]
                else:
                    targets = [data]
            elif content.startswith("["):
                data = json.loads(content)
                if isinstance(data, list):
                    targets = data
                elif isinstance(data, dict) and "targets" in data:
                    targets = data["targets"]
            else:
                # JSONL format (multiple lines)
                for line in content.split("\n"):
                    line = line.strip()
                    if line and line.startswith("{"):
                        try:
                            targets.append(json.loads(line))
                        except json.JSONDecodeError:
                            continue
        print(f"\nLoaded {len(targets)} targets from {args.input}")
    else:
        # Demo targets for testing
        print("\nNo input file, using demo targets...")
        targets = [
            {
                "target_id": "hf:model:meta-llama/Llama-3.1-8B",
                "source": "huggingface",
                "tipo_target": "model",
                "name": "meta-llama/Llama-3.1-8B",
                "url": "https://huggingface.co/meta-llama/Llama-3.1-8B",
                "popularity": {"downloads": 1500000, "likes": 2500},
                "metadata": {"has_training_section": False, "pipeline_tag": "text-generation"},
            },
            {
                "target_id": "hf:model:mistralai/Mistral-7B-v0.1",
                "source": "huggingface",
                "tipo_target": "model",
                "name": "mistralai/Mistral-7B-v0.1",
                "url": "https://huggingface.co/mistralai/Mistral-7B-v0.1",
                "popularity": {"downloads": 2000000, "likes": 3000},
                "metadata": {"has_training_section": False, "pipeline_tag": "text-generation"},
            },
            {
                "target_id": "hf:dataset:wikipedia",
                "source": "huggingface",
                "tipo_target": "dataset",
                "name": "wikipedia",
                "url": "https://huggingface.co/datasets/wikipedia",
                "popularity": {"downloads": 5000000, "likes": 500},
                "metadata": {"has_training_section": True, "declared_datasets": ["Wikipedia dumps"]},
            },
            {
                "target_id": "ollama:model:llama3",
                "source": "ollama",
                "tipo_target": "model",
                "name": "llama3",
                "url": "https://ollama.com/library/llama3",
                "popularity": {"pulls": 100000},
                "metadata": {},
            },
        ]
    
    # Generate enhancements
    generator = EnhancementGenerator()
    targets_to_process = targets[:args.limit]
    
    print(f"\nGenerating enhancements for {len(targets_to_process)} targets...")
    print("-" * 60)
    
    packages = generator.generate_batch(targets_to_process)
    
    # Calculate impact
    impact = calculate_impact(packages)
    
    print(f"\n📊 GENERATION STATS")
    print(f"   Generated: {generator.stats['generated']}")
    print(f"   Skipped: {generator.stats['skipped']}")
    print(f"   Errors: {generator.stats['errors']}")
    
    print(f"\n📈 TRANSPARENCY ANALYSIS")
    print(f"   No disclosure: {impact['transparency']['no_disclosure']} ({impact['transparency']['no_disclosure_pct']}%)")
    print(f"   Partial: {impact['transparency']['partial_disclosure']}")
    print(f"   Full: {impact['transparency']['full_disclosure']}")
    
    print(f"\n⚖️  EU AI ACT COMPLIANCE")
    print(f"   Avg compliance score: {impact['eu_ai_act']['avg_compliance_score']}%")
    print(f"   Fully compliant: {impact['eu_ai_act']['fully_compliant']}")
    
    print(f"\n🎯 POTENTIAL IMPACT")
    print(f"   Models needing enhancement: {impact['potential_impact']['models_needing_enhancement']}")
    print(f"   If 5% accept: {impact['potential_impact']['if_5pct_accept']} model cards with CROVIA")
    print(f"   If 10% accept: {impact['potential_impact']['if_10pct_accept']} model cards with CROVIA")
    print(f"   If 20% accept: {impact['potential_impact']['if_20pct_accept']} model cards with CROVIA")
    
    if not args.dry_run and packages:
        os.makedirs(args.output, exist_ok=True)
        
        # Save markdown files
        for pkg in packages:
            safe_name = pkg.target_name.replace("/", "_").replace(":", "_")
            md_path = os.path.join(args.output, f"{safe_name}.md")
            with open(md_path, "w", encoding="utf-8") as f:
                f.write(pkg.to_markdown())
        
        # Save impact report
        report_path = os.path.join(args.output, "impact_report.json")
        with open(report_path, "w", encoding="utf-8") as f:
            json.dump(impact, f, indent=2)
        
        print(f"\n✅ Saved {len(packages)} enhancement packages to {args.output}/")
    
    print("=" * 60)
